### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by marc0tjevp** [guglicap/wal-discord#2] opened 2018-05-23 14:41 UTC
What are the exact steps to install this, I don't understand the wiki that well. At this point I have cloned the repo and have Discord + Betterdiscord installed.

**Comment by guglicap** [comment] 2018-05-23 17:01
Thanks for the feedback.

At this point all you need to do is symlink the `wal-discord` script to somewhere in your $PATH.

For example, here's my $PATH: 
```
~ % echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/home/goo/bin/links
~ % 
```

in my case, I would symlink `wal-discord` to `/home/goo/bin/links` by running
`ln -s /absolute/path/to/repo/wal-discord /home/goo/bin/links`

if your $PATH doesn't include a folder in your $HOME directory you can symlink it to any of the other folders in $PATH, `/usr/local/bin` for example, so the command would become `sudo ln -s /absolute/path/to/repo/wal-discord /usr/local/bin`

you should then be able to run `wal-discord` without any problems.

Don't run the script like `/absoulte/path/to/repo/wal-discord` as that's the cause of #1 and I'm currently working on solving it.

Note: some terminal emulators must be restarted after symlinking.

**Comment by guglicap** [comment] 2018-05-23 17:02
Thanks for the feedback.

At this point all you need to do is symlink the `wal-discord` script to somewhere in your $PATH.

For example, here's my $PATH: 
```
~ % echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/home/goo/bin/links
~ % 
```

in my case, I would symlink `wal-discord` to `/home/goo/bin/links` by running
`ln -s /absolute/path/to/repo/wal-discord /home/goo/bin/links`

if your $PATH doesn't include a folder in your $HOME directory you can symlink it to any of the other folders in $PATH, `/usr/local/bin` for example, so the command would become `sudo ln -s /absolute/path/to/repo/wal-discord /usr/local/bin`

you should then be able to run `wal-discord` without any problems.

Don't run the script like `/absoulte/path/to/repo/wal-discord` as that's the cause of #1 and I'm currently working on solving it.

Note: some terminal emulators must be restarted after symlinking.

**Comment by guglicap** [comment] 2018-05-23 17:10
Thanks for the feedback.

At this point all you need to do is symlink the `wal-discord` script to
somewhere in your $PATH.

For example, here's my $PATH:
```
~ % echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/home/goo/bin/links
~ %
```

in my case, I would symlink `wal-discord` to `/home/goo/bin/links` by
running
`ln -s /absolute/path/to/repo/wal-discord /home/goo/bin/links`

if your $PATH doesn't include a folder in your $HOME directory you can
symlink it to any of the other folders in $PATH, `/usr/local/bin` for
example, so the command would become `sudo ln -s
/absolute/path/to/repo/wal-discord /usr/local/bin`

you should then be able to run `wal-discord` without any problems.

Don't run the script like `/absoulte/path/to/repo/wal-discord` as that's
the cause of #1 and I'm currently working on solving it.

Note: some terminal emulators must be restarted after symlinking.

Il giorno mer 23 mag 2018 alle ore 16:42 Marco van Poortvliet <
notifications@github.com> ha scritto:

**Comment by marc0tjevp** [comment] 2018-05-23 17:22
Thanks for the reply. I am now able to run wal-discord. Maybe I still did something wrong but the files in ~/.config/wal-discord seem to be broken (Link (broken) (inode/symlink)), which gives me this output

```
Error: File to import not found or unreadable: colors.scss.
        on line 1 of .config/wal-discord/backend.scss
        from line 1 of .config/wal-discord/master.scss
>> @import 'colors.scss';

   ^
```

**Comment by marc0tjevp** [comment] 2018-05-23 17:28
It seems like symlink colors.scss is broken. It's parent folder is /home/marco/.config/wal-discord, but the folder is empty.

**Comment by guglicap** [comment] 2018-05-23 17:33
`colors.scss` should point to `$HOME/.cache/wal/colors.scss`

please post the output of `ls -l /home/marco/.config/wal-discord`

**Comment by marc0tjevp** [comment] 2018-05-23 17:37
```
drwx------ 2 marco marco  4096 May 23 19:13 backends
lrwxrwxrwx 1 marco marco    17 May 23 19:13 backend.scss -> backends/wal.scss
lrwxrwxrwx 1 marco marco    34 May 23 19:13 colors.scss -> /home/marco/.cache/wal/colors.scss
-rw-rw-r-- 1 marco marco 10904 May 23 19:13 master.scss
```
There is no wal folder in my .cache folder.

**Comment by guglicap** [comment] 2018-05-23 17:40
that's weird, it should work. 
does `/home/marco/.cache/wal/` exist? 
if not, then your wal installation might be doing something different. 
maybe try running `wal` again.  

EDIT:

what's your wal version? 
you can find out by running `wal -v` 
also please post the output of `echo $XDG_CACHE_DIR`

**Comment by marc0tjevp** [comment] 2018-05-23 19:05
I tried reinstalling `wall`, I'm on version 3.0.0. The script runs now and creates the style.css file in `.cache/wal-discord/`. I used `@import "file:///home/marco/.cache/wal-discord/style.css";` in the Custom CSS tab but nothing seems to change, the file is populated tho. echo $XDG_CACHE_DIR outputs a blank line.

**Comment by guglicap** [comment] 2018-05-23 21:23
Hmm, it seems like you're right. 
I think I must have messed up something while testing it so that it was still loading beautifuldiscord css somehow and so I thought it was working.

I'll look into creating a way to generate a BetterDiscord theme.

**Comment by guglicap** [comment] 2018-05-25 14:48
Closing this as I added a way to generate a BetterDiscord theme, if you encounter problems with that please open another issue.

**Closed as completed by guglicap** 2018-05-25 14:48 UTC
